- package.json
- src/services/l1-ingestion/service.ts
- src/services/run.ts
- src/services/server/service.ts
- test/config/hardhat.config.ts
- test/l1-transport/basic-tests.spec.ts
Adds a basic set of tests for `TransactionEnqueued`, mainly using this as a chance to make sure that CI is working as expected.
> Added initial Enqueue tests

- src/client/client.ts
- src/db/transport-db.ts
- src/services/l1-ingestion/handlers/sequencer-batch-appended.ts
- src/services/l1-ingestion/service.ts
- src/services/server/service.ts
- src/types/api-types.ts
- test/unit-tests/services/l1-ingestion/handlers/sequencer-batch-appended.spec.ts
Adds a new endpoint `/eth/syncing` to represent that we're still synchronizing information from L1. Maybe `/eth/` prefix should be changed though.
> api: add syncing endpoint

- .github/workflows/push-to-integration-repo.yml
Adds the github action for pushing to the integration repo, depends on https://github.com/ethereum-optimism/optimism-integration/pull/61
> gitflows: push to integration repo

- src/db/transport-db.ts
- src/services/l1-ingestion/service.ts
- src/services/server/service.ts
- src/types/api-types.ts
Makes the response for `/eth/syncing` a little better, using `transactionIndex` instead of `block`. @tynes should we replace the `/eth/` prefix? If so, `/l2/`?
> api: improve `syncing` response

- src/db/transport-db.ts
- src/services/l1-ingestion/service.ts
- src/services/server/service.ts
`getHighestL2BlockNumber()` will just officially return `null` when not set. Also fixes an off-by-one error that made clients think we were never done syncing.
> Minor tweaks to fix sync statuses

- src/db/transport-db.ts
- src/services/l1-ingestion/service.ts
Infura does some *infura*iating caching that, while efficient, means we can't simply replace our providers with Infura and expect everything to work. This PR fixes that issue.
> l1-ingestion: fix so we can sync without infura's caching

- src/services/server/service.ts
Adds the endpoint `/eth/context/blocknumber/:number` which is used for getting the initial timestamp on startup based on the deploy height of the ctc
> feat: context by height endpoint

- package.json
- src/services/l1-ingestion/service.ts
- src/services/run.ts
- src/services/server/service.ts
- src/utils/index.ts
- src/utils/validation.ts
- yarn.lock
Also I made it so `@eth-optimism/dev` now has all of our dev dependencies already installed so we don't need to bloat our `package.json` anymore.
Other than that, main thing is to use new version of `service-base` that uses an `optionSettings` as a general purpose way for setting defaults, validation functions.
> feat: use new base service with prettier config settings

- src/services/l2-ingestion/service.ts
Closes https://github.com/ethereum-optimism/data-transport-layer/issues/51
Another solution would be to manage the start and end blocks such that this function is only called with sane arguments. That feels a little more ideal, but this definitely will prevent invalid queries. Thoughts @kfichter?
> fix: prevent syncsequencerblock bad query

- src/services/l2-ingestion/handlers/transaction.ts
Legacy sequencer uses `nonce` instead of `queueIndex`. Need to handle that case so we can make replicas of those older sequencers.
> Fix queue index for legacy sequencer

- src/services/l2-ingestion/service.ts
- src/services/main/service.ts
- src/services/run.ts
- src/services/server/service.ts
Basically forces L2 sync to stop after a certain point. Useful if you want to bootstrap as a replica but continue on your own. Automatically switches to providing L1 results for newer blocks because the L2 results won't exist.
> Add a jank temporary sync method

- src/services/server/service.ts
Fixes a bug where the latest transaction would always be the L2 synced transaction, even if L1 transactions had a higher index.
> fix: ensure latest transaction will always be displayed

- src/services/l2-ingestion/service.ts
By default, never stop syncing the L2 when sync from L2 is enabled
> config: default stop l2 sync at block value

- package.json
- yarn.lock
Without this, `yarn build` fails.
> build: install typescript dev dependency

- src/services/l2-ingestion/service.ts
This was missed in the original pass (https://github.com/ethereum-optimism/data-transport-layer/pull/73)
> Re-organize single log line to new format

- src/services/run.ts
Having a hardcoded default Chain ID tends to cause a lot of issues for users who don't realize that the value has a default, especially if that default is wrong. This PR removes the default and forces users to provide the Chain ID as an explicit input.
> fix: Remove default Chain ID

- package.json
- src/services/server/service.ts
- yarn.lock
[express-pino-logger](https://github.com/pinojs/express-pino-logger) is an out of the box, efficient, standardized solution for logging express requests information
- build: install express-pino-logger
- refactor: use express-pino-logger for logging express requests
> Use express-pino-logger

- src/services/l1-ingestion/handlers/sequencer-batch-appended.ts
- src/services/l1-ingestion/handlers/state-batch-appended.ts
- src/services/l1-ingestion/handlers/transaction-enqueued.ts
- src/types/event-handler-types.ts
- test/unit-tests/services/l1-ingestion/handlers/transaction-enqueued.spec.ts
`parseEvent` was always syncronous, thus the asyncronous wrapper was unnecessary.
> refactor: remove unnecessary asyncronous wrapper around syncronous code

- src/services/l1-ingestion/service.ts
- src/services/run.ts
Default of 12 is too low. 35 is much safer. Possible addition here would be to add a warning log if a confirmation depth < ~15 is used.
> fix: Bump default confs to 35

- package.json
- src/services/server/service.ts
- yarn.lock
**Description**
This PR removes `express-pino-logger` because it was really noisy and there was no way to use `pino-pretty` to filter out subobjects. This is a desired feature of `pino-pretty` and they are open to supporting it, see https://github.com/pinojs/pino-pretty/issues/132
It will now print the minimal information that we need when http requests come in. This is because these logs are very helpful when developing/debugging. A new script is added `yarn start:local` which pipes the output of the app into `pino-pretty`
**Additional context**
I have spoken to @snario about these changes and we agreed on them being doable. Using `express-pino-logger` could be a future thing if we run into scaling issues or submit a PR to `pino-pretty`
**Metadata**
- Fixes #[Link to Issue]
> logging: log only required things

- src/services/l2-ingestion/service.ts
**Description**
There currently exists a bug by which the data-transport-layer doesn't sync exactly to the tip. It constantly stays one block behind the tip. This fixes that bug. The off by one is accounted for in `handleSequencerBlock`
**Additional context**
This is required to unblock infra providers
**Metadata**
- Fixes #[Link to Issue]
> l2-service: fix trailing by one bug
